name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

env:
  TEST: SomeTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          curl --request POST --url $TEST'/api/cron'
