name: Cron
on:
  schedule:
    - cron: '0 7 * * *'

env:
  SECRETAPI: ${{ secrets.API_SECRET }}
  FRONTURL: ${{ secrets.FRONT_END_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          curl --request POST --url $FRONTURL'/api/cron' --header 'Authorization: Bearer '$SECRETAPI
